Algoritmo "ListaAtividade2-2"

Var
salario, financiamento: inteiro
Inicio
escreval("Financiamento Reinaldo")
escreval("qual seu salario?")
leia(salario)
escreval("Qual valor de financiamento voce quer?")
leia(financiamento)

se salario * 5 >= financiamento entao
   escreval("Voce conseguiu o financiamento")
   senao
        escreval("Obrigado por nos consultar")
   fimse

Fimalgoritmo