Algoritmo "ListaAtividade2-1"

Var
num : inteiro
Inicio
escreval("Algoritmo para ver numero primo")
escreval("Escreva um numero inteiro positivo")
leia(num)

   se num < 0 então
       escreval("ERRO! NUMERO NEGATIVO DETECTADO")
   interrompa
   senao
        se (num % 2 = 0) entao
        escreval("esse numero é par!")
        senão
             Escreval("esse numero é impar!")
        fimse
   fimse


Fimalgoritmo